pinout: 4
fps: 5
snapshot_duration: 5
script: ./start-webcam-fridge.sh
port: 3336
resolution: 1280x720
ssh_key: ~/.ssh/sanantonio
user: pi
host: raspberrypi
remote_path: /home/pi/node_programs/Home-Monitoring-Raspberry-Pi-Node/static/snapshots/fridge
angle: -90
window_size: 7